// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pifsemcuxyvwxibzrfbb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpZnNlbWN1eHl2d3hpYnpyZmJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNTc4ODEsImV4cCI6MjA2MTgzMzg4MX0.4qGSFCQlCMvC_DN7hF8jJsszUIOXfcd42wnawH0Hs5s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);